### PR TITLE
fixed: caret updated only for current tab; broken statusbar color after restart; black caret

### PR DESCRIPTION
**Pull request by veksha**
related issue: "caret updated only for current tab" - https://github.com/Alexey-T/CudaText/issues/4560

`+` two bugs fixed: broken statusbar color and black caret:

https://user-images.githubusercontent.com/275333/201506934-32ecaf8c-2c1f-4981-a7ac-485fa8358fbd.mp4

### CODE REVIEW

**Comment by veksha** [comment]
please read comments, especially about `APPSTATE_API_SUBCOMMANDS`.
I don't know what it is, but after this event statusbar is loaded and ready to be painted in color.
seems no other nice way to wait for statusbar load.

**Comment by Alexey-T** [comment]
regress: if Cud opens w/o Git file (GitStatus not active), statusbar is not colored by vim mode (because APPSTATE_API_SUBCOMMANDS goes from GitStatus when it calls app_proc(...SUBCOMMANDS...)).

**Comment by Alexey-T** [comment]
also I added some short info about APPSTATE_ values to the [API wiki](https://wiki.freepascal.org/CudaText_API#Events_-_State_changes)

**Comment by Alexey-T** [comment]
I checked that on_state is fired when ALL statusbar cells are inited. this code always shows 'info-here: True'.
```
    def on_state(self, ed_self, state):
        if state==APPSTATE_CONFIG_REREAD:
            h = app_proc(PROC_GET_MAIN_STATUSBAR, '')
            index = statusbar_proc(h, STATUSBAR_FIND_CELL, value=20)
            print('cfg reread,', 'info-here:', index is not None)
```
so statusbar is fully filled when we get APPSTATE_CONFIG_REREAD. no?

**Comment by veksha** [comment]
pushed new changes.
timer is used instead of event.

**Comment by veksha** [comment]
sometimes this happens:
image

but with timer it is better now.

**Comment by CudaText-addons** [comment]
```
        if state == APPSTATE_CONFIG_REREAD:
            self.update_caret()
```
did you test how plug applies statusbar color after OptionsEditor changes "ui_statusbar_panels"? i did not test.

**Comment by CudaText-addons** [comment]
tested. plugin handles it not 100% ok-- its cell "--Command--" becomes the first. can it be the last after Cud applies the option? for this, func 'update_statusbar' had "delete_vim_cell"

**Comment by veksha** [comment]
git_status icon also becomes 1st (or 2nd) must be before Msg cell.
different issue?

**Comment by Alexey-T** [comment]
GitStatus is ok, it has this moving of cell:
```
        # app config was reloaded, and Git cell was moved to 0 - then move it
        if app_api_version()>='1.0.430':
            if index_new==0:
                statusbar_proc(BAR_H, STATUSBAR_MOVE_CELL, index=index_new, value=index_info-1)
```

**Comment by veksha** [comment]
image

**Comment by Alexey-T** [comment]
somehow conflicts with VimMode.

**Comment by Alexey-T** [comment]
GitStatus has `  if index_new==0:` - this must be changed?

**Comment by veksha** [comment]
> somehow conflicts with VimMode.

you are right.

**Comment by Alexey-T** [comment]
GitStatus `if index_new==0:`  - try to change to `if index_new<2:`

**Comment by veksha** [comment]
yes, this works for git_status icon.

**Comment by Alexey-T** [comment]
updated GitStatus in git

**Comment by veksha** [comment]
changed to:
```python
if state == APPSTATE_CONFIG_REREAD:
            self.update_statusbar(delete_vim_cell=True)
```

**Pull request merged**
